ACTransit.RestroomFinder.Web/Controllers/ContactController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;
using ACTransit.Framework.Logging;
using X.PagedList;

using ACTransit.RestroomFinder.Domain.Dto;
using ACTransit.RestroomFinder.Domain.Infrastructure;
using ACTransit.RestroomFinder.Domain.Service;
using ACTransit.RestroomFinder.Web.Controllers.Base;
using ACTransit.RestroomFinder.Web.Infrastructure;
using ACTransit.RestroomFinder.Web.Models;

namespace ACTransit.RestroomFinder.Web.Controllers
{
    [Authorize]
    public class ContactController : BaseController
    {
        private const string Ascending = "ascending";
        private const string Namefieldname = "ContactName";
        
        public async Task<ActionResult> Index(string searchContactName, string sortField, string sortDirection, string searchServiceProvider, int page = 1)
        {
            var contactModel = new ContactViewModel();

            //Persit information for next page load
            ViewBag.SearchContactName = searchContactName;
            ViewBag.SearchServiceProvider = searchServiceProvider;
            ViewBag.SortField = sortField ?? Namefieldname;
            ViewBag.SortDirection = sortDirection ?? Ascending;
            ViewBag.Page = page;

            using (var service = new ContactService())
            {
                contactModel.Contacts = await service.GetContactsAsync(new ContactSearchContext
                {
                    Name = searchContactName,
                    ServiceProvider = searchServiceProvider,
                    SortField = sortField,
                    SortDirection = sortDirection == "descending" ? SortDirection.Descending : SortDirection.Ascending,
                    PageNumber = page
                });
            }

            return View(contactModel);
        }

        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenContactCreator })]
        public ActionResult Create()
        {
            try
            {
                var contactModel = new ContactViewModel();
                return View(contactModel);
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Create", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ContactViewModel contactModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var service = new ContactService(PrincipalName))
                    {
                        var newContact = await service.SaveContactAsync(contactModel.CurrentContact);
                        return RedirectToAction("Index", new
                        {
                            searchContactName = Session["SearchContactName"],
                            searchServiceProvider = Session["SearchServiceProvider"]
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Create", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(contactModel);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id, int page = 1, string sortField = "AddDateTime", string sortDirection = "Descending")
        {
            var contactViewModel = new ContactViewModel();

            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                //Persit information for next page load
                ViewBag.SortField = sortField ?? "AddDateTime";
                ViewBag.SortDirection = sortDirection ?? "Ascending";
                ViewBag.Page = page;

                using (var contactService = new ContactService(PrincipalName))
                {
                    contactViewModel.CurrentContact = await contactService.GetContactAsync(id);
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Details", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(contactViewModel);
        }

        // GET: Contact/Edit/5
        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenContactEditor })]
        public async Task<ActionResult> Edit(int? id)
        {
            var contactModel = new ContactViewModel();

            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                using (var service = new ContactService())
                {
                    var contact = await service.GetContactAsync(id.Value);

                    if (contact == null)
                        return HttpNotFound();
                    contactModel.CurrentContact = contact;
                }

                return View(contactModel);
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Edit", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // POST: Contact/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ContactViewModel contactModel)
        {
            if (contactModel == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            try
            {
                if (ModelState.IsValid)
                {
                    using (var service = new ContactService(PrincipalName))
                    {
                        var contact = await service.SaveContactAsync(contactModel.CurrentContact);
                        return RedirectToAction("Index", new
                        {
                            searchContactName = Session["SearchContactName"],
                            searchServiceProvider = Session["SearchServiceProvider"],
                            sorField = Session["SortField"],
                            sortDirection = Session["SortDirection"],
                            page = Session["page"]
                        });
                    }
                }

                return View(contactModel);
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Edit", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }


        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenContactEditor })]
        public async Task<ActionResult> Delete(int? id)
        {
            var contactViewModel = new ContactViewModel();

            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                using (var service = new ContactService())
                    contactViewModel.CurrentContact = await service.GetContactAsync(id);

                if (contactViewModel == null)
                    return HttpNotFound();
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.Delete", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(contactViewModel);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                using (var service = new ContactService(PrincipalName))
                {
                    var isDeleted = await service.SoftDeleteContactAsync(id);

                    if (!isDeleted)
                        return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.ContactController.DeleteConfirmed", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            //Return to main page
            return RedirectToAction("Index", new
            {
                searchContactName = Session["SearchContactName"],
                searchServiceProvider = Session["SearchServiceProvider"],
                sorField = Session["SortField"],
                sortDirection = Session["SortDirection"],
                page = Session["page"]
            });
        }

    }
}

ACTransit.RestroomFinder.Web/Controllers/DeviceController.cs
using System;
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;

using X.PagedList;

using ACTransit.DataAccess.RestroomFinder;
using ACTransit.RestroomFinder.Domain.Infrastructure;
using ACTransit.RestroomFinder.Domain.Service;
using ACTransit.RestroomFinder.Web.Controllers.Base;
using ACTransit.RestroomFinder.Web.Infrastructure;

using Device = ACTransit.RestroomFinder.Domain.Dto.Device;

namespace ACTransit.RestroomFinder.Web.Controllers
{
    [Authorize]
    public class DeviceController : BaseController
    {
        private const string Namefieldname = "LastUsed";
        private const string Ascending = "ascending";

        private readonly RestroomContext _db = new RestroomContext();

        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> Index(string deviceGuid, string searchModel, string searchOS, string sortField, string sortDirection, int page = 1, string showActive = "True")
        {
            IPagedList<Device> pagedDevices;

            //Persit information for next page load
            ViewBag.SearchDevice = deviceGuid;
            ViewBag.SearchModel = searchModel;
            ViewBag.SearchOS = searchOS;
            ViewBag.SortField = sortField ?? Namefieldname;
            ViewBag.ShowActive = showActive;
            ViewBag.SortDirection = sortDirection ?? Ascending;
            ViewBag.Page = page;

            bool? active;
            if (showActive.Equals("All", StringComparison.CurrentCultureIgnoreCase))
                active = null;
            else
                active = showActive == "True";

            using (var service = new UserDeviceService())
            {
                pagedDevices = await service.GetDevicesAsync(new DeviceSearchContext
                {
                    DeviceGuid = deviceGuid,
                    Model = searchModel,
                    Os = searchOS,
                    Active = active,
                    SortField = sortField,
                    SortDirection = sortDirection == "descending" ? SortDirection.Descending : SortDirection.Ascending,
                    PageNumber = page
                });
            }

            return View(pagedDevices);
        }

        [HttpPost]
        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> ActivateDevice(long deviceId, string searchBadge, string searchModel, string searchOS, string sortField, string sortDirection, int? page, string showActive = "True", bool activate = true)
        {
            using (var service = new UserDeviceService(PrincipalName))
            {
                if (activate)
                    await service.ActivateDevice(deviceId);
                else
                    await service.InActivateDevice(deviceId);
            }
            return RedirectToAction("Index", new { searchBadge, searchModel, searchOS, sortField, sortDirection, page, showActive });
        }
    }
}

ACTransit.RestroomFinder.Web/Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

using X.PagedList;

using ACTransit.RestroomFinder.Domain.Dto;
using ACTransit.RestroomFinder.Domain.Infrastructure;
using ACTransit.RestroomFinder.Domain.Service;
using ACTransit.RestroomFinder.Web.Controllers.Base;
using ACTransit.RestroomFinder.Web.Infrastructure;
using System.Web.Helpers;

namespace ACTransit.RestroomFinder.Web.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private const string Ascending = "ascending";
        private const string Namefieldname = "Name";

        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> Index(string searchBadge, string sortField, string sortDirection, int page = 1, string showActive = "True")
        {
            IPagedList<User> pagedUsers;

            //Persit information for next page load
            ViewBag.SearchBadge = searchBadge;
            ViewBag.SortField = sortField ?? Namefieldname;
            ViewBag.ShowActive = showActive;
            ViewBag.SortDirection = sortDirection ?? Ascending;
            ViewBag.Page = page;

            bool? active;
            if (showActive.Equals("All", StringComparison.CurrentCultureIgnoreCase))
                active = null;
            else
                active = showActive.Equals("True", StringComparison.InvariantCultureIgnoreCase);

            using (var service = new UserDeviceService())
            {
                pagedUsers = await service.GetUsersAsync(new UserSearchContext
                {
                    Badge = searchBadge,
                    Active = active,
                    SortField = sortField,
                    SortDirection = sortDirection == "descending" ? SortDirection.Descending : SortDirection.Ascending,
                    PageNumber = page
                });
            }

            return View(pagedUsers);
        }

        [HttpPost]
        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> ActivateUser(int userId, string searchBadge, string searchModel, string searchOS, string sortField, string sortDirection, int? page, string showActive = "True", bool activate = true)
        {
            using (var service = new UserDeviceService(PrincipalName))
            {
                if (activate)
                    await service.ActivateUser(userId);
                else
                    await service.InActivateUser(userId);
            }
            return RedirectToAction("Index", new { searchBadge, searchModel, searchOS, sortField, sortDirection, page, showActive });
        }
    }
}

ACTransit.RestroomFinder.Web/Views/Shared/NotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "NotFound";
}

<div class="col-md-12">
    <h1 class="text-danger"> Sorry, it's not here.</h1>
    <h4 class="text-danger"> We don't have a page at this address "@ViewBag.Message". Can we help you find something?</h4>
    <ul>
        <li>Check the web address again.</li>
        <li>Go to <a href='@Href("~")'>home</a>.</li>
    </ul>
    <br />
</div>

ACTransit.RestroomFinder.Web/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>ACTransit RestroomFinder ▶ @ViewBag.Title</title>
    <link rel="home" id="ApplicationRoot" href="@Url.Action("Index","Home", new {area=""})" />
    <link rel="SHORTCUT ICON" href="~/favicon.ico" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/sass")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("head", required: false)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="navbar-fixed-bottom">
        <p>&copy; @DateTime.Now.Year - AC Transit</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>

ACTransit.RestroomFinder.Web/Views/Shared/_EmployeeSearch.cshtml
<div>
    <div class="modal fade" id="badge-list-container" tabindex="-1" role="dialog" aria-labelledby="badge-list-label" aria-hidden="true">
        <div class="modal-dialog m-width">
            <div class="modal-content" style="min-height: 200px;">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">&times;</a>
                    <br />
                </div>
                <div class="modal-body">
                    <div class="form-inline" style="margin-bottom: 10px;">
                        <label class="control-label">Search by</label>
                        <select id="badge-search-by" class="form-control">
                            <option value="badge">Badge</option>
                            <option value="firstName">First Name</option>
                            <option value="lastName" selected="selected">Last Name</option>
                        </select>
                        <input type="text" id="badge-search-textbox" class="form-control" /><span id="badge-search-button" class="glyphicon glyphicon-search" style="cursor: pointer;margin-left: 10px"></span>
                        <input type="hidden" id="hdnValue" />
                    </div>
                    <div class="table-responsive">
                        <table id="badge-list" class="list gray mousesensitive" style="padding-right: 100px;">
                            <thead>
                                <tr>
                                    <th>Last Name</th>
                                    <th>First Name</th>
                                    <th>Department</th>
                                    <th>Business Phone</th>
                                    <th>Cell Phone</th>
                                    <th>Badge</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer bottom">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var EmployeeSearch = {
        value:'',
        url: '',
        modalId : '#badge-list-container',
        show: function (url) {
            EmployeeSearch.url = url;
            var prom = $.Deferred();
            $(EmployeeSearch.modalId).modal('show');

            $(EmployeeSearch.modalId).modal();
            $(EmployeeSearch.modalId).on('hidden.bs.modal', function (e) {
                prom.resolve(EmployeeSearch.value);
            });

            return prom;
        },
        hide: function () { $(EmployeeSearch.modalId).modal('hide'); },

        onClose:null,

        initial:function() {
            var searchData = [];

            $('#badge-list-container').on('shown.bs.modal', function (e) {
                $("#badge-search-textbox").focus();
            });

            $("#badge-search-textbox").keydown(function (e) {
                var key = e.charCode ? e.charCode : e.keyCode ? e.keyCode : 0;
                if (key != 13) return;
                e.preventDefault();
                $("#badge-search-button").click();
            });

            $("#badge-search-button").click(function () {
                var id = $("#badge-search-textbox").val();
                var searchBy = '';
                if ($.isNumeric(id)) {
                    $("#badge-search-by").val('badge');
                }
                searchBy = $("#badge-search-by").val();
                var url = EmployeeSearch.url;
                Ajax.ajax(url, {
                    type: "POST",
                    data: {
                        badge: (searchBy == "badge" ? id : null),
                        lastName: (searchBy == "lastName" ? id : null),
                        firstName: (searchBy == "firstName" ? id : null)
                    }
                }, waitBox).done(function (data) {
                    var result = '';
                    searchData = data;
                    $.each(data, function (i, item) {
                        result += '<tr id="badge-list-' + i + '">' +
                            '<td>' + item.LastName + '</td>' +
                            '<td>' + item.FirstName + '</td>' +
                            '<td>' + item.Department + '</td>' +
                            '<td>' + item.BusinessPhone + '</td>' +
                            '<td>' + item.CellPhone + '</td>' +
                            '<td>' + item.Badge + '</td>' +
                            '</tr>';
                    });
                    $("#badge-list tbody").html(result);
                    $("#badge-list tbody tr").click(function () {
                        var idx = $(this).attr("id").replace("badge-list-", "");
                        postBadgeFilterUpdate(data[idx].Badge.trim());
                    });
                });

                function postBadgeFilterUpdate(newBadge) {
                    EmployeeSearch.value = newBadge;
                    //$("#hdnValue").val(newBadge);
                    $('#badge-list-container').modal('hide');
                }

            });

            $(EmployeeSearch.modalId).on('hidden.bs.modal', function (e) {
                if (EmployeeSearch.onClose != null)
                    EmployeeSearch.onClose(EmployeeSearch.value);
            });
        },

        getEmployees: function (condition) {
            var searchBy='name';
            if ($.isNumeric(condition))
                searchBy = 'badge';
            var url = EmployeeSearch.url;
            return Ajax.ajax(url, {
                type: "POST",
                data: {
                    badge: (searchBy == "badge" ? condition : null),
                    name: (searchBy == "name" ? condition : null),
                }
            }, waitBox);
        },
        providEmployeeSource: function (req, res) {
            var term = req.term;
            if (term.length > 2) {
                EmployeeSearch.getEmployees(term).done(function (data) {
                    var source = [];
                    var matcher = new RegExp($.ui.autocomplete.escapeRegex(term), "i");
                    if (data && data.length) {
                        for (var i = 0; i < data.length; i++) {
                            var d = data[i].Badge;// + ' - ' + data[i].Name + "( " + data[i].LoginId + " )";
                            if (data[i].Name) d = d + ' - ' + data[i].Name;
                            if (data[i].LoginId) d = d + " (" + data[i].LoginId + ")";
                            if (matcher.test(d))
                                source.push({ value: data[i].Badge, label: d, name: data[i].Name });
                        }
                    }
                    if (source.length == 0)
                        source.push({ value: '', label: '', name: ''});
                    res(source);
                }
                ).fail(function () { res(); });
            } else {
                res();
            }
        }

    }
    $(function() {
        
    });

</script>

ACTransit.RestroomFinder.Web/Views/Shared/_Menu.cshtml
@using System.Configuration;
@using ACTransit.RestroomFinder.Web.Infrastructure

<div class="navbar navbar-darkgradient" style="margin-bottom:0; z-index: 1000;">
    <div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href='#' class="dropdown-toggle" data-toggle="dropdown">Restrooms<b class="caret"></b></a> @* removed  data-toggle="dropdown" to be clickable!*@
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("View and Search Restrooms", "Index", "Restroom")</li>
                        @if (TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenAdmin) || TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenRestroomCreator))
                        {
                            <li>@Html.ActionLink("Add a New Restroom", "Create", "Restroom")</li>
                        }
                    </ul>
                </li>
                @if (TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenAdmin) || TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenApplicationAccessEditor))
                {
                    <li class="dropdown">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">Users and Devices<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manage Users", "index", "User")</li>
                            <li>@Html.ActionLink("Manage Users And Devices", "Index", "UserDevice")</li>
                            <li>@Html.ActionLink("Manage Devices", "Index", "Device")</li>
                        </ul>
                    </li>
                }
                <li class="dropdown">
                    <a href='#' class="dropdown-toggle" data-toggle="dropdown">Restroom Contacts<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("View and Search Contact", "Index", "Contact")</li>
                        @if (TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenAdmin) || TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenContactCreator))
                        {
                            <li>@Html.ActionLink("Add a New Contact", "Create", "Contact")</li>
                        }
                    </ul>
                </li>

                @*<li class="dropdown">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">Contacts and Vendors<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manage Contact Information", "index", "Contact")</li>
                        </ul>
                    </li>*@
                @*<li class="dropdown">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">Notifications<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manage Notifications", "index", "Notification")</li>
                        </ul>
                    </li>*@
                <li class="dropdown">
                    <a href='#' class="dropdown-toggle" data-toggle="dropdown">Restroom Reports<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="@(ConfigurationManager.AppSettings["Report.RestroomList.Location"] ?? string.Empty)" target="_blank">Restroom Report</a></li>
                        <li><a href="@(ConfigurationManager.AppSettings["Report.RestroomFeedback.Location"] ?? string.Empty)" target="_blank">Feedback Report</a></li>
                        <li>@Html.ActionLink("Print Report", "Print", "Restroom")</li>
                        <li>@Html.ActionLink("Restroom Contact Report", "RestroomContactReport", "Restroom")</li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

ACTransit.RestroomFinder.Web/Views/Shared/_WaitBox.cshtml
<div id="divWaitBox" style="z-index: 10000">
    <div class="first"></div>@*This div causes the page not to be editable/clickable, to remove this feature, simply reemove the dive or rename the class to something else. *@
    <div class="second"><span>Waiting...</span>@*We could replace this part with a little Icon*@</div>
</div>

<script>
    var waitBox;
    $(function (e) {
        "use strict";
        waitBox = $("#divWaitBox").modalBox();
    });
</script>