ACTransit.RestroomFinder.Web/Models/RestroomViewModel.cs
using ACTransit.Framework.Extensions;
using ACTransit.RestroomFinder.Domain.Dto;
using ACTransit.RestroomFinder.Domain.Enums;
using ACTransit.RestroomFinder.Domain.Service;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using X.PagedList;

namespace ACTransit.RestroomFinder.Web.Models
{
    public class RestroomViewModel
    {
        private static List<SelectListItem> _statuses;
        private static List<SelectListItem> _drinkingWaterOptions;
        private static List<SelectListItem> _restroomTypes;
        private static List<SelectListItem> _scopes;
        private static List<SelectListItem> _toiletOptions;
        private static List<SelectListItem> _feedbackNeed;
        private static List<SelectListItem> _contacts;
        private static List<SelectListItem> _searchStatuses;
        private static List<SelectListItem> _searchScopes;
        private static List<SelectListItem> _searchReviewStatuses;
        private static List<SelectListItem> _searchToiletOptions;

        public IPagedList<Restroom> ApprovedRestrooms { get; set; } = new PagedList<Restroom>(null, 1, 1);

        public IPagedList<Feedback> RestroomFeedback { get; set; } = new PagedList<Feedback>(null, 1, 1);

        public IPagedList<RestroomContact> RestroomContacts { get; set; } = new PagedList<RestroomContact>(null, 1, 1);

        public IEnumerable<Restroom> ReviewRestrooms { get; set; } = Enumerable.Empty<Restroom>();
        public IEnumerable<RestroomHistory> RestroomHistory { get; set; } = Enumerable.Empty<RestroomHistory>();

        public IEnumerable<RestroomsByDivision> RestroomsByDivision { get; set; } = Enumerable.Empty<RestroomsByDivision>();

        public IEnumerable<RestroomsByRoutes> RestroomsByRoute { get; set; } = Enumerable.Empty<RestroomsByRoutes>();

        public Restroom CurrentRestroom { get; set; } = new Restroom
        {
            StatusListId = (int)RestroomEnums.RestroomApprovalStatus.Approved,
            Country = "USA",
            //Active = true,
            RestroomType = "NON-PAID"
        };

        public List<SelectListItem> ToiletGenders { get; set; } = new List<SelectListItem>();

        public RestroomContact CurrentContact { get; set; }

        public Feedback CurrentFeedback { get; set; } = new Feedback
        {
            InspectionPassed = false,
            NeedsCleaning = true,
            NeedsRepair = true,
            NeedsSupply = true
        };

        public IEnumerable<RestroomContactReport> RestroomContactReport { get; set; } = Enumerable.Empty<RestroomContactReport>();

        public static List<SelectListItem> RestroomTypes => _restroomTypes ?? (_restroomTypes = new RestroomService().GetRestroomTypes());

        public static List<SelectListItem> DrinkingWaterOptions => _drinkingWaterOptions ?? (_drinkingWaterOptions = new RestroomService().GetDrinkingWaterOptions());

        public static List<SelectListItem> Scopes => _scopes ?? (_scopes = new RestroomService().GetVisibilityStatuses());

        public static List<SelectListItem> Statuses => _statuses ?? (_statuses = new RestroomService().GetRestroomStatuses());

        public static List<SelectListItem> ToiletOptions => _toiletOptions ?? (_toiletOptions = new RestroomService().GetToiletOptions());

        public static List<SelectListItem> SearchStatuses => _searchStatuses ?? (_searchStatuses = new RestroomService().GetRestroomStatuses(true));

        public static List<SelectListItem> SearchToiletOptions => _searchToiletOptions ?? (_searchToiletOptions = new RestroomService().GetToiletOptions(true));

        public static List<SelectListItem> VisibilityStatuses => _searchScopes ?? (_searchScopes = new RestroomService().GetVisibilityStatuses(true));

        public static List<SelectListItem> ReviewStatuses => _searchReviewStatuses ?? (_searchReviewStatuses = new RestroomService().GetPendingReviewStatuses());


        public static List<SelectListItem> FeedbackNeed => _feedbackNeed ?? (_feedbackNeed = new FeedbackService().GetFeedbackNeed());

        public static string GetDrinkingWaterOptionName(string waterOptionValue)
        {
            return DrinkingWaterOptions.Where(s => s.Value.Equals(waterOptionValue.ToString(), System.StringComparison.CurrentCultureIgnoreCase))
                                       .Select(s => s.Text)
                                       .FirstOrDefault();
        }

        public static string GetRestroomType(string restroomType)
        {
            return RestroomTypes.Where(s => s.Value.Equals(restroomType, System.StringComparison.CurrentCultureIgnoreCase))
                .Select(s => s.Text)
                .FirstOrDefault();
        }

        public static string GetStatusName(int statusId)
        {
            return Statuses.Where(s => s.Value.Equals(statusId.ToString(), System.StringComparison.CurrentCultureIgnoreCase))
                           .Select(s => s.Text)
                           .FirstOrDefault();
        }

        public static string GetVisibilityName(bool? visibilityValue)
        {
            return Scopes.Where(s => s.Value.Equals(visibilityValue.ToString(), System.StringComparison.CurrentCultureIgnoreCase))
                        .Select(s => s.Text)
                        .FirstOrDefault();
        }

        public static string GetIsToiletAvailableName(bool isToiletAvailableValue)
        {
            return ToiletOptions.Where(s => s.Value.Equals(isToiletAvailableValue.ToString(), System.StringComparison.CurrentCultureIgnoreCase))
                        .Select(s => s.Text)
                        .FirstOrDefault();
        }

        public static string GetChangeColorCode(string newValue, string oldValue)
        {
            string changeType;
            string parsedNewValue = newValue?.Trim() ?? string.Empty;
            string parsedOldValue = oldValue?.Trim() ?? string.Empty;

            if (parsedNewValue.Equals(parsedOldValue, System.StringComparison.InvariantCultureIgnoreCase))
                changeType = RestroomEnums.RestroomChangeType.None.Description();
            else
            {
                if (string.IsNullOrEmpty(parsedNewValue) && !string.IsNullOrEmpty(parsedOldValue))
                    changeType = RestroomEnums.RestroomChangeType.Deleted.Description();
                else if (!string.IsNullOrEmpty(parsedNewValue) && string.IsNullOrEmpty(parsedOldValue))
                    changeType = RestroomEnums.RestroomChangeType.Added.Description();
                else
                    changeType = RestroomEnums.RestroomChangeType.Updated.Description();
            }

            return changeType;
        }
    }
}

ACTransit.RestroomFinder.Web/Controllers/RestroomController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using ACTransit.RestroomFinder.Domain.Dto;
using ACTransit.RestroomFinder.Domain.Enums;
using ACTransit.RestroomFinder.Web.Models;
using ACTransit.RestroomFinder.Web.Controllers.Base;
using ACTransit.RestroomFinder.Domain.Infrastructure;
using ACTransit.RestroomFinder.Domain.Service;
using ACTransit.RestroomFinder.Web.Infrastructure;

namespace ACTransit.RestroomFinder.Web.Controllers
{
    [Authorize]
    public class RestroomController : BaseController
    {
        [AllowAnonymous]
        public async Task<ActionResult> Index(string searchName,
                                              string searchLabelId,
                                              string searchAddress,
                                              string searchCity,
                                              string searchRouteSelection,
                                              string sortField = "RestroomName",
                                              string sortDirection = "Ascending",
                                              int page = 1,
                                              string statusId = "All",
                                              string showPublic = "All",
                                              string showToilet = "All",
                                              string showPendingReview = "All")
        {
            var restroomViewModel = new RestroomViewModel();
            try
            {
                //Persit information for next page load
                Session["SearchName"] = searchName;
                Session["SearchLabelId"] = searchLabelId;
                Session["SearchAddress"] = searchAddress;
                Session["SearchCity"] = searchCity;
                Session["SearchRoutes"] = searchRouteSelection;
                Session["SortField"] = sortField ?? "RestroomName";
                Session["StatusId"] = statusId;
                Session["ShowPublic"] = showPublic;
                Session["showToilet"] = showToilet;
                Session["ShowPendingReview"] = showPendingReview;
                Session["SortDirection"] = sortDirection ?? "Ascending";
                Session["Page"] = page;

                using (var service = new RestroomService())
                {
                    restroomViewModel.ApprovedRestrooms = await service.GetApprovedRestroomsAsync(new RestroomSearchContext
                    {
                        Name = searchName,
                        LabelId = searchLabelId,
                        Address = searchAddress,
                        City = searchCity,
                        Routes = string.IsNullOrEmpty(searchRouteSelection) ? null : searchRouteSelection.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries),
                        Public = showPublic == "All" ? (bool?)null : showPublic == "True",
                        StatusId = statusId == "All" ? (int?) null : int.Parse(statusId),
                        HasToilet = showToilet == "All" ? (bool?)null : showToilet == "True",
                        PendingReview = showPendingReview == "All" ? (bool?)null : showPendingReview == "True",
                        SortField = sortField,
                        SortDirection = sortDirection.Equals("Ascending", StringComparison.CurrentCultureIgnoreCase)
                                            ? System.Web.Helpers.SortDirection.Ascending
                                            : System.Web.Helpers.SortDirection.Descending,
                        PageNumber = page
                    });
                    restroomViewModel.ToiletGenders = service.GetToiletGenders();
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.RestroomController.Index", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(restroomViewModel);
        }

        [AllowAnonymous]
        public async Task<ActionResult> History(int? id,
            string sortField = "UpdDateTime",
            string sortDirection = "Ascending")
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Session["RestroomId"] = id.Value;
            Session["SortField"] = sortField ?? "RestroomName";
            Session["SortDirection"] = sortDirection ?? "Ascending";

            sortDirection = sortDirection != null && sortDirection.Equals("Ascending", StringComparison.CurrentCultureIgnoreCase)
                ? System.Web.Helpers.SortDirection.Ascending.ToString()
                : System.Web.Helpers.SortDirection.Descending.ToString();

            var restroomViewModel = new RestroomViewModel();
            try
            {
                using (var service = new RestroomService())
                {
                    restroomViewModel.RestroomHistory = await service.GetRestroomHistory(id.Value, sortField, sortDirection);
                    restroomViewModel.ToiletGenders = service.GetToiletGenders();
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.RestroomController.History", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(restroomViewModel);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id, int page = 1, string sortField = "AddDateTime", string sortDirection = "Descending")
        {
            var restroomViewModel = new RestroomViewModel();

            try
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                //Persit information for next page load
                ViewBag.SortField = sortField ?? "AddDateTime";
                ViewBag.SortDirection = sortDirection ?? "Ascending";
                ViewBag.Page = page;

                using (var restroomService = new RestroomService())
                {
                    restroomViewModel.CurrentRestroom = await restroomService.GetApprovedRestroomAsync(id);
                    restroomViewModel.ToiletGenders = restroomService.GetToiletGenders();
                }

                using (var feedbackService = new FeedbackService())
                {
                    restroomViewModel.RestroomFeedback = await feedbackService.GetRestroomFeedbackAsync(new FeedbackSearchContext
                    {
                        RestroomId = id,
                        SortField = sortField,
                        SortDirection = sortDirection != null && sortDirection.Equals("Ascending", StringComparison.CurrentCultureIgnoreCase)
                        ? System.Web.Helpers.SortDirection.Ascending
                        : System.Web.Helpers.SortDirection.Descending,
                        PageNumber = page
                    });
                }

                using (var contactService = new ContactService())
                {
                    restroomViewModel.RestroomContacts = await contactService.GetContactsAsync(new ContactSearchContext
                    {
                        SortField = "ServiceProvider",
                        SortDirection = System.Web.Helpers.SortDirection.Ascending,
                        PageNumber = 1,
                        PageSize = 1
                    });
                }
                
                if (restroomViewModel.CurrentRestroom?.ContactId != null)
                    restroomViewModel.CurrentContact = restroomViewModel.RestroomContacts.FirstOrDefault(c =>
                                                           c.ContactId == (int)restroomViewModel.CurrentRestroom.ContactId) ??
                                                       new RestroomContact();

                if (restroomViewModel == null)
                    return HttpNotFound();

            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.RestroomController.Details", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(restroomViewModel);
        }

        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenRestroomCreator })]
        public async Task<ActionResult> Create()
        {
            try
            {
                var restroomModel = new RestroomViewModel();
                using (var contactService = new ContactService())
                {
                    restroomModel.RestroomContacts = await contactService.GetContactsAsync(new ContactSearchContext
                    {
                        SortField = "ServiceProvider",
                        SortDirection = System.Web.Helpers.SortDirection.Ascending,
                        PageNumber = 1,
                        PageSize = 1
                    });
                }
                restroomModel.ToiletGenders = new RestroomService().GetToiletGenders();
                return View(restroomModel);
            }
            catch (Exception ex)
            {
                Logger.WriteError("ACTransit.RestroomFinder.Web.RestroomController.Create", ex);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RestroomViewModel restroomModel)
        {
            try
            {

ACTransit.RestroomFinder.Web/Views/Restroom/RestroomContactReport.cshtml
@model  ACTransit.RestroomFinder.Web.Models.RestroomViewModel

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@section Head {
    @Styles.Render("~/Content/magicsuggestcss")
}

<style>
    th {
        white-space: nowrap;
        word-wrap: break-word;
    }

    .headers th {
        border: 1px solid white !important;
        white-space: nowrap;
        background-color: rgb(68,114, 196);
        color: white;
    }

        .headers th a {
            color: white;
        }

    select {
        box-sizing: border-box;
        border-radius: 4px;
    }

    td .glyphicon {
        font-size: 16pt;
    }

    @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
        table, thead, tbody, th, td, tr {
            display: block;
        }
            /*Hide table headers (but not display: none;, for accessibility) */
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

        tr {
            margin: 0 0 1rem 0;
        }

            tr:nth-child(odd) {
                background: #ccc;
            }

        td {
            border: none;
            border-bottom: 1px solid #eee;
            position: relative;
            padding-left: 50%;
            text-align: left !important;
        }

            td:before {
                position: absolute;
                top: 0;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
                font-weight: bold;
            }

            td:nth-of-type(1):before {
                content: "Restroom Name";
            }

            td:nth-of-type(2):before {
                content: "Owned Service Provider";
            }

            td:nth-of-type(3):before {
                content: "Cleaned Service Provider";
            }

            td:nth-of-type(4):before {
                content: "Repaired Service Provider";
            }

            td:nth-of-type(5):before {
                content: "Supplied Service Provider";
            }

            td:nth-of-type(6):before {
                content: "Security Gates Service Provider";
            }

            td:nth-of-type(7):before {
                content: "Security Locks Service Provider";
            }
    }
</style>

@{
    ViewBag.Title = "Restroom Contact";
}
<div id="SearchPanel" class="panel-collapse collapse">
    <div>
        <br />
    </div>
    @using (Html.BeginForm("RestroomContactReport", "Restroom", FormMethod.Post, new { id = "SearchForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-inline" style="line-height:20px;">
            @Html.Hidden("SortField", Session["SortField"] as string)
            @Html.Hidden("SortDirection", Session["SortDirection"] as string)
        </div>
    }
</div>

<br />
<div>
    <fieldset>
        <button class="btn btn-info hidden-print" id="print">Print </button>
    </fieldset>
</div>

<br />

<div class="row">
    <br />
    <div class="col-md-12">
        @{
            if (!Model.RestroomContactReport.Any())
            {
                <span style="font-weight: bold; margin-left: 20px;">No restroom contact found for the current search criteria.</span>
            }
            else
            {
                <table class="contacttable">
                    <thead>
                        <tr class="headers">
                            <th style="min-width: 170px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="RestroomName" class="sortable">Restroom Name</a>
                            </th>
                            <th style="min-width: 170px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="LabelId" class="sortable">ID No</a>
                            </th>
                            <th style="min-width: 170px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="StatusName" class="sortable">Status</a>
                            </th>
                            <th style="width: 85px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="OwnedServiceProvider" class="sortable">Owned Service Provider</a>
                            </th>
                            <th style="min-width: 160px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="CleanedServiceProvider" class="sortable">Cleaned Service Provider</a>
                            </th>
                            <th style="width: 110px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="RepairedServiceProvider" class="sortable">Repaired Service Provider</a>
                            </th>
                            <th style="width: 65px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="SuppliedServiceProvider" class="sortable">Supplied Service Provider</a>
                            </th>
                            <th style="width: 50px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="SecurityGateServiceProvider" class="sortable">Security/Gates Service Provider</a>
                            </th>
                            <th style="width: 175px;">
                                <div class="glyphicon glyphicon-sort"></div>
                                <a href="#" data-sortfield="SecurityLocksServiceProvider" class="sortable">Security/Locks Service Provider</a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.RestroomContactReport)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RestroomName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LabelId)
                                </td>
                                <td>
                                    @Html.Raw(item.Status == "Pending" ? "<span style='color:darkorange;'>Pending</span>" : item.Status == "Out of Service" ? "<span style='color:red;'>Out of Service</span>" : item.Status)
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.OwnedContactId })'>@Html.DisplayFor(modelItem => item.OwnedServiceProvider)</a>
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.CleanedContactId })'>@Html.DisplayFor(modelItem => item.CleanedServiceProvider)</a>
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.RepairedContactId })'>@Html.DisplayFor(modelItem => item.RepairedServiceProvider)</a>
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.SuppliedContactId })'>@Html.DisplayFor(modelItem => item.SuppliedServiceProvider)</a>
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.SecurityGateContactId })'>@Html.DisplayFor(modelItem => item.SecurityGateServiceProvider)</a>
                                </td>
                                <td>
                                    <a href='@Url.Action("Edit", "Contact", new { id = item.SecurityLockContactId })'>@Html.DisplayFor(modelItem => item.SecurityLockServiceProvider)</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        }
        @Html.Hidden("SortField", Session["SortField"] as string)
        @Html.Hidden("SortDirection", Session["SortDirection"] as string)
    </div>
</div>


@section Scripts{
    <script src="~/Scripts/site.js"></script>
    <script>
        $(document).ready(function () {

            initPage({ hasSortTable: true, hasSearchPanels: true });

            setRestroomTableStyle($(".contacttable"));

            // Hack to make the responsive table work correctly with desired styling
            $(window).resize(function () {
                setRestroomTableStyle($(".contacttable"));
            });

            $("#print").click(function (e) {
                $('.contacttable').table2excel({
                    name: "WorkSheet-All",
                    filename: "Restroom Contact List",
                    fileext: ".xls",
                    preserveColors: true
                });

            });
        });

        function decodeEntities(encodedString) {
            var textArea = document.createElement('textarea');
            textArea.innerHTML = encodedString;
            return textArea.value;
        }

    </script>
}

ACTransit.RestroomFinder.Web/Views/Restroom/RestroomContactsPartial.cshtml
@model ACTransit.RestroomFinder.Web.Models.RestroomViewModel



<table class="contacttable" style="max-height: 500px;">
    <thead>
        <tr>
            <th style="width:70px;"></th>
            <th>
                @Html.DisplayName("Service Provider")
            </th>
            <th>
                @Html.DisplayName("Contact Name")
            </th>
            <th>
                @Html.DisplayName("Email")
            </th>
            <th>
                @Html.DisplayName("Phone")
            </th>
            <th>
                @Html.DisplayName("Address")
            </th>
            <th style="width: 70px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contact in Model.RestroomContacts)
        {
            <tr>
                <td>
                    @Html.RadioButtonFor(modelItem => Model.CurrentRestroom.ContactId, contact.ContactId, new { id = "" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact.ServiceProvider)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => contact.Address)
                </td>
                <td style="text-align: center;">
                </td>
            </tr>
        }
    </tbody>
</table>

@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">

    $(document).ready(function () {

        setRestroomTableStyle($(".contacttable"));

        // Hack to make the responsive table work correctly with desired styling
        $(window).resize(function () {
            setRestroomTableStyle($(".contacttable"));
        });
    });
</script>