ACTransit.RestroomFinder.Web/Controllers/UserDeviceController.cs
using System;
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Collections.Generic;

using ACTransit.RestroomFinder.Domain.Dto;
using ACTransit.RestroomFinder.Domain.Infrastructure;
using ACTransit.RestroomFinder.Domain.Service;
using ACTransit.RestroomFinder.Web.Controllers.Base;
using ACTransit.RestroomFinder.Web.Infrastructure;

namespace ACTransit.RestroomFinder.Web.Controllers
{
    [Authorize]
    public class UserDeviceController : BaseController
    {
        private const string Ascending = "ascending";
        private const string Namefieldname = "LastLogon";

        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> Index(string searchBadge, string searchModel, string searchOS, string sortField, string sortDirection, string showActive = "True")
        {
            IEnumerable<UserDevice> userDevices;

            //Persit information for next page load
            ViewBag.SearchBadge = searchBadge;
            ViewBag.SearchModel = searchModel;
            ViewBag.SearchOS = searchOS;
            ViewBag.SortField = sortField ?? Namefieldname;
            ViewBag.ShowActive = showActive;
            ViewBag.SortDirection = sortDirection ?? Ascending;

            bool? active;
            if (showActive.Equals("All", StringComparison.CurrentCultureIgnoreCase))
                active = null;
            else
                active = showActive == "True";

            using (var service = new UserDeviceService())
            {
                userDevices = await service.GetUserDevicesAsync(new UserDeviceSearchContext
                {
                    Badge = searchBadge,
                    Model = searchModel,
                    Os = searchOS,
                    Active = active,
                    SortField = sortField,
                    SortDirection = sortDirection == "descending" ? SortDirection.Descending : SortDirection.Ascending,
                });
            }

            return View(userDevices);
        }

        [HttpPost]
        [TokenAuthorization(Tokens = new[] { TokenAuthorizationHelper.TokenAdmin, TokenAuthorizationHelper.TokenApplicationAccessEditor })]
        public async Task<ActionResult> ActivateUserDevice(int userId, long deviceId, string searchBadge, string searchModel, string searchOS, string sortField, string sortDirection, int? page, string showActive = "True", bool activate = true)
        {
            using (var service = new UserDeviceService(PrincipalName))
            {
                if (activate)
                    await service.ActivateUserDevice(userId, deviceId);
                else
                    await service.InActivateUserDevice(userId, deviceId);
            }
            return RedirectToAction("Index", new { searchBadge, searchModel, searchOS, sortField, sortDirection, page, showActive });
        }
    }
}

ACTransit.RestroomFinder.Web/Views/UserDevice/Index.cshtml
@using ACTransit.RestroomFinder.Web.Infrastructure
@using ACTransit.RestroomFinder.Web.Models

@model IEnumerable<ACTransit.RestroomFinder.Domain.Dto.UserDevice>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<style>
    th {
        width: 350px;
        white-space: nowrap;
    }

    .worktable {
        height: 500px;
        display: block;
        overflow-y: auto;
        padding: 0;
    }

    input[type=text] {
        box-sizing: border-box;
        border-radius: 4px;
        background-color: white;
        background-image: url('./content/images/searchicon.png');
        background-position: 1px 0px;
        background-repeat: no-repeat;
        padding-left: 25px;
        width: 150px;
    }

    select {
        box-sizing: border-box;
        border-radius: 4px;
    }

    .panel-heading .accordion-toggle:after {
        font-family: 'Glyphicons Halflings';
        content: "\2212";
        float: left;
        color: black;
        margin-right: 4px;
    }

    .panel-heading .accordion-toggle.collapsed:after {
        content: "\2b";
    }

    #search-panel-user-device .accordion-toggle:after {
        font-family: 'Glyphicons Halflings';
        content: "\e113";
        float: left;
        color: black;
        margin-right: 4px;
        font-size: large;
    }

    #search-panel-user-device .accordion-toggle.collapsed:after {
        content: "\e114";
    }
</style>

@{
    ViewBag.Title = "Manage Users and Devices";

    var userIsAdmin = TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenAdmin);
    var userCanEdit = userIsAdmin || TokenAuthorizationHelper.HasAccess(TokenAuthorizationHelper.TokenApplicationAccessEditor);

    string TrimTo(string str, int length, string followByif)
    {
        if (string.IsNullOrEmpty(str) || str.Length < length)
        {
            return str;
        }

        return str.Substring(0, length) + followByif;
    }
}

<h2>Manage Users and Devices</h2>

<br />
<div class="row">
    <div class="col-lg-12">
        <div id="HeaderOptions">
            <div id="SearchPanelGroup" class="panel-group col-md-10" style="padding: 0;">
                <div class="panel panel-default" style="padding: 0;">
                    <div id="search-panel-user-device" class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle collapsed" data-toggle="collapse" href="#SearchPanel" style="text-decoration: none;">Search Options</a>
                        </h4>
                    </div>
                    <div id="SearchPanel" class="panel-collapse collapse">
                        <div>
                            <br />
                        </div>
                        @using (Html.BeginForm("Index", "UserDevice", FormMethod.Get, new { id = "SearchForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <p>
                                &nbsp;Badge:&nbsp;@Html.TextBox("SearchBadge", ViewBag.SearchBadge as string)
                                &nbsp;Model:&nbsp;@Html.TextBox("SearchModel", ViewBag.SearchModel as string)
                                &nbsp;OS:&nbsp;@Html.TextBox("SearchOS", ViewBag.SearchOS as string)
                                &nbsp;Status:&nbsp;@Html.DropDownList("ShowActive", new SelectList(RestroomViewModel.SearchStatuses, "Value", "Text"))
                                @Html.Hidden("Page", ViewBag.Page as int?)
                                @Html.Hidden("SortField", ViewBag.SortField as string)
                                @Html.Hidden("SortDirection", ViewBag.SortDirection as string)
                                &nbsp;<input type="submit" value="Search" class="btn btn-primary" onclick="$('#Page').val('');" />
                                &nbsp;<input type="submit" value="Reset Search" class="btn btn-primary" onclick="resetForm($('#SearchForm'));" />
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @{
        var groupByItems = Model.GroupBy(m => $"{m.Name} ({m.Badge}) {(string.IsNullOrEmpty(m.JobTitle) ? string.Empty : $"- {m.JobTitle}")}", m => new
        {
            m.DeviceModel,
            m.DeviceOS,
            m.DeviceSessionId,
            m.LastLogon,
            m.DeviceGuid,
            m.Active,
            m.CanUse,
            m.UserId,
            m.DeviceId
        }).OrderBy(m => m.Key);

        var counter = 0;

    }
    <div id="results-panel-group" class="panel-group">

        @foreach (var group in groupByItems)
        {
            <div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="accordion-toggle collapsed" style="text-decoration: none;" data-toggle="collapse" href='@($"#pnlresult{counter}")'>@Html.DisplayFor(modelItem => group.Key)</a>
                    </div>
                    <div id='@($"pnlresult{counter}")' class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table list highlight mousesensitive" style="margin-bottom: 20px; margin-left: 25px;">
                                <thead>
                                <tr style="background-color: #f9f9fa">
                                    <th>DeviceModel</th>
                                    <th>DeviceOS</th>
                                    <th>Device Session</th>
                                    <th>LastLogon</th>
                                    <th>Device Guid</th>
                                    <th>Active</th>
                                    <th>Can be used</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach (var item in group)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.DeviceModel)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DeviceOS)</td>
                                        <td>@TrimTo(item.DeviceSessionId, 10, "...")</td>
                                        <td>@Html.DisplayFor(modelItem => item.LastLogon)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DeviceGuid)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Active)</td>
                                        <td>@Html.DisplayFor(modelItem => item.CanUse)</td>
                                        <td>
                                            @{
                                                if (userCanEdit)
                                                {

                                                    using (Html.BeginForm("ActivateUserDevice", "UserDevice", FormMethod.Post))
                                                    {
                                                        @Html.Hidden("SearchBadge", ViewBag.SearchBadge as string)
                                                        @Html.Hidden("SearchModel", ViewBag.SearchModel as string)
                                                        @Html.Hidden("SearchOS", ViewBag.SearchOS as string)
                                                        @Html.Hidden("ShowActive", ViewBag.ShowActive as string)
                                                        @Html.Hidden("Page", ViewBag.Page as int?)
                                                        @Html.Hidden("SortField", ViewBag.SortField as string)
                                                        @Html.Hidden("SortDirection", ViewBag.SortDirection as string)
                                                        @Html.Hidden("userId", item.UserId)
                                                        @Html.Hidden("deviceId", item.DeviceId)
                                                        if (item.Active)
                                                        {
                                                            @Html.Hidden("activate", false)
                                                            <input type="submit" value="Disable" style="background: none; border-width: 0px; color: blue; text-decoration: underline;" />
                                                        }
                                                        else
                                                        {
                                                            @Html.Hidden("activate", true)
                                                            <input type="submit" value="Enbable" style="background: none; border-width: 0px; color: blue; text-decoration: underline;" />
                                                        }
                                                    }
                                                }
                                            }
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            counter++;
        }
    </div>

</div>

<br />

@section Scripts{
    <script src="~/Scripts/site.js"></script>
    <script>
        $(document).ready(function () {
            initPage({ hasSortTable: true, hasSearchPanels: true });

            const panels = $.cookie();
            for (let panel in panels) {
                if (panels.hasOwnProperty(panel)) {
                    if ($("#" + panel).hasClass('panel-collapse'))
                        $("#" + panel).collapse("show");
                }
            }
        });
    </script>
}

